// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {internal} from '../models';

export function ApplyGameModeToProcess(arg1:number):Promise<void>;

export function GetCPUGovernor():Promise<string>;

export function GetGameModeStatus():Promise<internal.GameModeStatus>;

export function GetProcesses():Promise<internal.ProcessResult>;

export function GetServices():Promise<Array<internal.ServiceInfo>>;

export function GetStartupApps():Promise<Array<internal.StartupApp>>;

export function KillProcesses(arg1:Array<number>,arg2:boolean):Promise<Array<internal.KillResult>>;

export function ServiceAction(arg1:string,arg2:string):Promise<void>;

export function SetCPUGovernor(arg1:string):Promise<void>;

export function ToggleStartupApp(arg1:string,arg2:boolean):Promise<void>;
