// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyGameModeToProcess(arg1) {
  return window['go']['main']['App']['ApplyGameModeToProcess'](arg1);
}

export function GetCPUGovernor() {
  return window['go']['main']['App']['GetCPUGovernor']();
}

export function GetGameModeStatus() {
  return window['go']['main']['App']['GetGameModeStatus']();
}

export function GetProcesses() {
  return window['go']['main']['App']['GetProcesses']();
}

export function GetServices() {
  return window['go']['main']['App']['GetServices']();
}

export function GetStartupApps() {
  return window['go']['main']['App']['GetStartupApps']();
}

export function KillProcesses(arg1, arg2) {
  return window['go']['main']['App']['KillProcesses'](arg1, arg2);
}

export function ServiceAction(arg1, arg2) {
  return window['go']['main']['App']['ServiceAction'](arg1, arg2);
}

export function SetCPUGovernor(arg1) {
  return window['go']['main']['App']['SetCPUGovernor'](arg1);
}

export function ToggleStartupApp(arg1, arg2) {
  return window['go']['main']['App']['ToggleStartupApp'](arg1, arg2);
}
